pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id("java").apply(false)
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

rootProject.name = 'mazes-demos'

include "MazeDemoFX", "MazeDemos", "SwingMazeDemo"
